apiVersion: v1
data:
  password: T2J2aW91c2x5IHRoaXMgaXNuJ3QgYSByZWFsIHBhc3N3b3Jk
kind: Secret
metadata:
  creationTimestamp: "2023-02-09T12:57:56Z"
  name: testsecret
  namespace: default
  resourceVersion: "162166"
  uid: 008e7028-db6c-4c38-8f37-a69a17150ad5
type: Opaque
