apiVersion: v1
kind: Pod
metadata:
  name: hostnetworkpod
  labels:
spec:
  hostNetwork: true
  containers:
  - name: hostnetwork
    image: alpine
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
