apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: normalpod
  name: normalpod
spec:
  containers:
  - image: alpine
    name: normalpod
    resources: {}
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
