apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: normalpod
  name: normalpod
spec:
  containers:
  - image: alpine
    name: normalpod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
