apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: labeller
  name: labeller
spec:
  containers:
  - image: bitnami/kubectl
    name: labeller
    resources: {}
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
  serviceAccount: labeller
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
