apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: test-allow-get-patch-namespace
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - patch
  - get
