apiVersion: v1
kind: Pod
metadata:
  name: noderootpod
  labels:
spec:
  containers:
  - name: noderootpod
    image: alpine
    volumeMounts:
    - mountPath: /host
      name: noderoot
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
  volumes:
  - name: noderoot
    hostPath:
      path: /
