apiVersion: v1
kind: Pod
metadata:
  name: noderootpod
  labels:
spec:
  hostPID: true
  containers:
  - name: noderootpod
    image: alpine
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]